### ISSUE TITLE
Missing add a comment feature as a logged user

### ISSUE THREAD

**Issue by astyltsvig** [BingoBois/DolphinNewsFrontend#29]
Right now we cant submit a comment as a logged user in the frontend

**Comment by radeonxray** [comment]
The issue is being looked in to. We had some issues with our Kubernetes (because I broke it) and the team took the oppertunity to upgrade and move the project to better and more powerfull hardware, while we fixed the issue. 

With the latest updates (c2bc8aaf7b820163fd27388f71c9ce1cafe064e3, 12f886f3822d75e4fb4ae5281580b970ce31936d, 1b49289d2d49de4e9102dbd5a83d1cab4d8dce82, 147edb1fd92ab6b9e0544ac1931bc187c6ffb24c ), it is possible to post comments to stories, though not as beuatiful as one might have wanted, but the basic functionality is there for now and we will continue to work on the feature.
